### ISSUE TITLE
when i click on 1099 the app crashes...

### ISSUE THREAD

**Issue by theoko** [thegrims/UsTaxes#123] opened 2021-02-21 07:49 UTC
just go to the website and click the 1099 button on the navigation menu

**Comment by thegrims** [comment] 2021-02-21 07:56
@theoko If you've entered data into the site previously and the data schema of the site changes, (when the 1099 PR was merged in) this can sometimes cause errors. Try opening the developer console, navigating to 'Application', and clicking the 'Clear Site Data' button. Let me know if that fixes the issue!

**Comment by zakpatterson** [comment] 2021-02-21 08:18
Hi @theoko, thanks for trying out the project. Can confirm, I see the same on a browser I tested this on last week, and the issue goes away if I use a fresh local storage. So I agree this is #94. For now we are just breaking the schema as we add features. Thanks for your interest in the project. Join our discord!

**Comment by theoko** [comment] 2021-02-21 15:19
> @theoko If you've entered data into the site previously and the data schema of the site changes, (when the 1099 PR was merged in) this can sometimes cause errors https://github.com/thegrims/UsTaxes/issues/94. Try opening the developer console, navigating to 'Application', clicking the 'Clear Site Data' button, and refreshing the page. Let me know if that fixes the issue!


I just tried it and it worked!

**Comment by zakpatterson** [comment] 2021-02-21 15:23
Thanks for trying! We'll close this as a duplicate of #94

**Closed by zakpatterson** 2021-02-21 15:23 UTC
